[build]
  command = "echo No build for this site, we are living on the edge"
  publish = "public"


[[redirects]]
  from = "/api/"
  to = "https://netease-cloud-music-api-yang1206.vercel.app/"
  force = true
  status = 200
